#!/bin/bash                                                                                                    

cd ~/alx-low_level_programming/
./git
cd ~/alx-low_level_programming/0x0C-more_malloc_free
