#!/bin/bash                                                                                                    

cd ~/alx-low_level_programming/
./git
cd ~/alx-low_level_programming/0x13-more_singly_linked_lists/
