#!/bin/bash                                                                                                    

cd ~/alx-low_level_programming/
./git
cd ~/alx-low_level_programming/0x14-bit_manipulation/
